### ISSUE TITLE
หลังจาก Pull Master มาแล้ว เจอ error ตอนเข้า dashboard หลังจากรัน rails s

### ISSUE THREAD

**Issue by teerasej** [rhearnorth/spfarm#13]
หลังจาก pull master ตัวล่าสุดมา รัน rails s แล้วเจอ error บนหน้าเว็บว่า

```
TypeError at /
no implicit conversion of nil into Array
```

เห็น @rhearnorth ทำการใส่ seed contract plan เข้ามาใหม่ เลยลองรัน `rake db:migrate` ดู เจอ error แบบด้านล่างจ้า

ควรทำยังไงต่ออ่ะ?

```
rake db:migrate
rake aborted!
LoadError: cannot load such file -- bundler/dep_proxy
/Users/teerasejjiraphatchandej/Desktop/SP/spfarm-project/config/boot.rb:3:in `<top (required)>'
/Users/teerasejjiraphatchandej/Desktop/SP/spfarm-project/config/application.rb:1:in `require_relative'
/Users/teerasejjiraphatchandej/Desktop/SP/spfarm-project/config/application.rb:1:in `<top (required)>'
/Users/teerasejjiraphatchandej/Desktop/SP/spfarm-project/Rakefile:4:in `require_relative'
/Users/teerasejjiraphatchandej/Desktop/SP/spfarm-project/Rakefile:4:in `<top (required)>'
/Users/teerasejjiraphatchandej/.rvm/gems/ruby-2.5.0@global/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'

Caused by:
LoadError: cannot load such file -- bundler/dep_proxy
/Users/teerasejjiraphatchandej/Desktop/SP/spfarm-project/config/boot.rb:3:in `<top (required)>'
/Users/teerasejjiraphatchandej/Desktop/SP/spfarm-project/config/application.rb:1:in `require_relative'
/Users/teerasejjiraphatchandej/Desktop/SP/spfarm-project/config/application.rb:1:in `<top (required)>'
/Users/teerasejjiraphatchandej/Desktop/SP/spfarm-project/Rakefile:4:in `require_relative'
/Users/teerasejjiraphatchandej/Desktop/SP/spfarm-project/Rakefile:4:in `<top (required)>'
/Users/teerasejjiraphatchandej/.rvm/gems/ruby-2.5.0@global/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'

Caused by:
LoadError: cannot load such file -- bundler/setup
/Users/teerasejjiraphatchandej/Desktop/SP/spfarm-project/config/boot.rb:3:in `<top (required)>'
/Users/teerasejjiraphatchandej/Desktop/SP/spfarm-project/config/application.rb:1:in `require_relative'
/Users/teerasejjiraphatchandej/Desktop/SP/spfarm-project/config/application.rb:1:in `<top (required)>'
/Users/teerasejjiraphatchandej/Desktop/SP/spfarm-project/Rakefile:4:in `require_relative'
/Users/teerasejjiraphatchandej/Desktop/SP/spfarm-project/Rakefile:4:in `<top (required)>'
/Users/teerasejjiraphatchandej/.rvm/gems/ruby-2.5.0@global/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)
```

**Comment by teerasej** [comment]
ตอนนี้ลองใช้ 

```
bundle exec rake db:create
bundle exec rake db:migrate 
bundle exec rake db:seed
```

แต่รันแล้วเหมือนไม่มีอะไรเกิดขึ้น 
พอรัน rails s แล้ว รันได้ไม่มีปัญหา

แต่พอกดเข้า `localhost:3000` แล้วเจอ error ตัวเดิมคือ

```
TypeError at /
no implicit conversion of nil into Array
```

ตอนนี้ log ที่เจอคือ

```
Processing by Devise::SessionsController#new as HTML
  Rendering /Users/teerasejjiraphatchandej/.rvm/gems/ruby-2.5.0/gems/devise-4.4.0/app/views/devise/sessions/new.html.erb withinlayouts/application
  Rendered /Users/teerasejjiraphatchandej/.rvm/gems/ruby-2.5.0/gems/devise-4.4.0/app/views/devise/shared/_links.html.erb (7.3ms)
  Rendered /Users/teerasejjiraphatchandej/.rvm/gems/ruby-2.5.0/gems/devise-4.4.0/app/views/devise/sessions/new.html.erb within layouts/application (680.4ms)
Completed 401 Unauthorized in 934ms (ActiveRecord: 4.6ms)

TypeError - no implicit conversion of nil into Array:
```

ถ้าเข้าผ่าน `localhost:3000/orders` จะเจอ log แบบนี้


```
Started GET "/orders" for 127.0.0.1 at 2018-02-28 18:30:32 +0700
Processing by OrdersController#index as HTML
Completed 401 Unauthorized in 3ms (ActiveRecord: 0.0ms)

NoMethodError - undefined method `admin?' for nil:NilClass:
```

ก่อนหน้านี้เข้าได้ ไม่มีปัญหานา

**Comment by rhearnorth** [comment]
Done
