### ISSUE TITLE
เจอ Error Uglifier ในการ deploy ขึ้น Heroku

### ISSUE THREAD

**Issue by teerasej** [rhearnorth/spfarm#8]
หลังจากใส่ CSS แล้ว ตอนสั่ง deploy heroku 

`Uglifier::Error: Unexpected token: name (Util). To use ES6 syntax, harmony mode must be enabled with Uglifier.new(:harmony => true).`

สังเกตว่า Error เกิดขึ้นในขั้นตอนรันคำสั่ง `Running: rake assets:precompile`
ตอนนี้ในการทดสอบรันคำสั่งเดียวกันในเครื่องปกติ ไม่เจอ error ทั้ง @rhearnorth และของพล

มีคำแนะนำวิธีแก้ไขที่ https://github.com/lautis/uglifier/issues/127 แต่ยังทดสอบไม่ได้ เพราะติดปัญหาอื่น

Log เต็มๆ 

```
 Personal    desolate-basin-65162
Overview  Resources  Deploy  Metrics  Activity  Access  Settings
Activity Feed  Build Log ID e692807d-96ca-466a-bd26-c5281bc3c01f
-----> Ruby app detected
-----> Compiling Ruby/Rails
-----> Using Ruby version: ruby-2.3.1
-----> Installing dependencies using bundler 1.15.2
       Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
       Warning: the running version of Bundler (1.15.2) is older than the version that created the lockfile (1.16.1). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
       Fetching gem metadata from https://rubygems.org/........
       Fetching version metadata from https://rubygems.org/..
       Fetching dependency metadata from https://rubygems.org/.
       Using concurrent-ruby 1.0.5
       Using minitest 5.11.1
       Using thread_safe 0.3.6
       Using builder 3.2.3
       Using erubi 1.7.0
       Using mini_portile2 2.3.0
       Using crass 1.0.3
       Using rack 2.0.3
       Using rake 12.3.0
       Using nio4r 2.2.0
       Using websocket-extensions 0.1.3
       Using mini_mime 1.0.0
       Using arel 8.0.0
       Using execjs 2.7.0
       Using method_source 0.9.0
       Using thor 0.19.4
       Using kaminari-core 1.1.1
       Using rb-fsevent 0.10.2
       Using ffi 1.9.18
       Using tilt 2.0.8
       Using selectize-rails 0.12.4.1
       Using aws_cf_signer 0.1.3
       Using bcrypt 3.1.11
       Using popper_js 1.12.9
       Using bundler 1.15.2
       Using json 1.8.6
       Using mime-types-data 3.2016.0521
       Using mimemagic 0.3.2
       Using unf_ext 0.0.7.4
       Using netrc 0.11.0
       Using coffee-script-source 1.12.2
       Using orm_adapter 0.5.0
       Using dotenv 2.2.1
       Using high_voltage 3.0.0
       Using multi_json 1.12.2
       Using pg 0.21.0
       Using puma 3.11.0
       Using turbolinks-source 5.0.3
       Using i18n 0.9.1
       Using tzinfo 1.2.4
       Using nokogiri 1.8.1
       Using rack-test 0.8.2
       Using sprockets 3.7.1
       Using warden 1.2.7
       Using mail 2.7.0
       Using autoprefixer-rails 7.2.4
       Using uglifier 4.1.2
       Using websocket-driver 0.6.5
       Using rb-inotify 0.9.10
       Using mime-types 3.1
       Using coffee-script 2.4.1
       Using unf 0.1.4
       Using turbolinks 5.0.1
       Using activesupport 5.1.4
       Using loofah 2.1.1
       Using sass-listen 4.0.0
       Using domain_name 0.5.20170404
       Using rails-dom-testing 2.0.3
       Using globalid 0.4.1
       Using activemodel 5.1.4
       Using jbuilder 2.7.0
       Using pundit 1.1.0
       Using rails-html-sanitizer 1.0.3
       Using sass 3.5.5
       Using http-cookie 1.0.3
       Using activejob 5.1.4
       Using activerecord 5.1.4
       Using carrierwave 0.11.2
       Using actionview 5.1.4
       Using rest-client 2.0.2
       Using kaminari-activerecord 1.1.1
       Using actionpack 5.1.4
       Using kaminari-actionview 1.1.1
       Using cloudinary 1.8.2
       Using actioncable 5.1.4
       Using actionmailer 5.1.4
       Using railties 5.1.4
       Using sprockets-rails 3.2.1
       Using kaminari 1.1.1
       Using momentjs-rails 2.17.1
       Using jquery-rails 4.3.1
       Using coffee-rails 4.2.2
       Using responders 2.4.0
       Using dotenv-rails 2.2.1
       Using bootstrap 4.0.0.beta3
       Using bourbon 4.3.4
       Using sass-rails 5.0.7
       Using rails 5.1.4
       Using datetime_picker_rails 0.0.7
       Using devise 4.4.0
       Using administrate 0.8.1
       Using devise_invitable 1.7.2
       Bundle complete! 45 Gemfile dependencies, 92 gems now installed.
       Gems in the groups development and test were not installed.
       Bundled gems are installed into ./vendor/bundle.
       Bundle completed (3.47s)
       Cleaning up the bundler cache.
       Warning: the running version of Bundler (1.15.2) is older than the version that created the lockfile (1.16.1). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
       The latest bundler is 1.16.1, but you are currently running 1.15.2.
       To update, run `gem install bundler`
-----> Installing node-v6.11.1-linux-x64
-----> Detecting rake tasks
-----> Preparing app for Rails asset pipeline
       Running: rake assets:precompile
       Yarn executable was not detected in the system.
       Download Yarn at https://yarnpkg.com/en/docs/install
       rake aborted!
       Uglifier::Error: Unexpected token: name (Util). To use ES6 syntax, harmony mode must be enabled with Uglifier.new(:harmony => true).
       /tmp/build_56936c9f1deb4f20e844ea2f278265c0/vendor/bundle/ruby/2.3.0/gems/uglifier-4.1.2/lib/uglifier.rb:236:in `parse_result'
       /tmp/build_56936c9f1deb4f20e844ea2f278265c0/vendor/bundle/ruby/2.3.0/gems/uglifier-4.1.2/lib/uglifier.rb:218:in `run_uglifyjs'
       /tmp/build_56936c9f1deb4f20e844ea2f278265c0/vendor/bundle/ruby/2.3.0/gems/uglifier-4.1.2/lib/uglifier.rb:168:in `compile'
       /tmp/build_56936c9f1deb4f20e844ea2f278265c0/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/uglifier_compressor.rb:53:in `call'
       /tmp/build_56936c9f1deb4f20e844ea2f278265c0/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/uglifier_compressor.rb:28:in `call'
       /tmp/build_56936c9f1deb4f20e844ea2f278265c0/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:75:in `call_processor'
       /tmp/build_56936c9f1deb4f20e844ea2f278265c0/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
       /tmp/build_56936c9f1deb4f20e844ea2f278265c0/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `reverse_each'
       /tmp/build_56936c9f1deb4f20e844ea2f278265c0/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `call_processors'
       /tmp/build_56936c9f1deb4f20e844ea2f278265c0/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:134:in `load_from_unloaded'
       /tmp/build_56936c9f1deb4f20e844ea2f278265c0/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:60:in `block in load'
       /tmp/build_56936c9f1deb4f20e844ea2f278265c0/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
       /tmp/build_56936c9f1deb4f20e844ea2f278265c0/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:44:in `load'
       /tmp/build_56936c9f1deb4f20e844ea2f278265c0/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:20:in `block in initialize'
       /tmp/build_56936c9f1deb4f20e844ea2f278265c0/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:47:in `load'
       /tmp/build_56936c9f1deb4f20e844ea2f278265c0/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/base.rb:66:in `find_asset'
       /tmp/build_56936c9f1deb4f20e844ea2f278265c0/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/base.rb:73:in `find_all_linked_assets'
       /tmp/build_56936c9f1deb4f20e844ea2f278265c0/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:142:in `block in find'
       /tmp/build_56936c9f1deb4f20e844ea2f278265c0/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:114:in `block (2 levels) in logical_paths'
       /tmp/build_56936c9f1deb4f20e844ea2f278265c0/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:228:in `block in stat_tree'
       /tmp/build_56936c9f1deb4f20e844ea2f278265c0/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:212:in `block in stat_directory'
       /tmp/build_56936c9f1deb4f20e844ea2f278265c0/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:209:in `each'
       /tmp/build_56936c9f1deb4f20e844ea2f278265c0/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:209:in `stat_directory'
       /tmp/build_56936c9f1deb4f20e844ea2f278265c0/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:227:in `stat_tree'
       /tmp/build_56936c9f1deb4f20e844ea2f278265c0/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:105:in `each'
       /tmp/build_56936c9f1deb4f20e844ea2f278265c0/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:105:in `block in logical_paths'
       /tmp/build_56936c9f1deb4f20e844ea2f278265c0/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:104:in `each'
       /tmp/build_56936c9f1deb4f20e844ea2f278265c0/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:104:in `logical_paths'
       /tmp/build_56936c9f1deb4f20e844ea2f278265c0/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:140:in `find'
       /tmp/build_56936c9f1deb4f20e844ea2f278265c0/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:185:in `compile'
       /tmp/build_56936c9f1deb4f20e844ea2f278265c0/vendor/bundle/ruby/2.3.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:68:in `block (3 levels) in define'
       /tmp/build_56936c9f1deb4f20e844ea2f278265c0/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/rake/sprocketstask.rb:147:in `with_logger'
       /tmp/build_56936c9f1deb4f20e844ea2f278265c0/vendor/bundle/ruby/2.3.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:67:in `block (2 levels) in define'
       /tmp/build_56936c9f1deb4f20e844ea2f278265c0/vendor/bundle/ruby/2.3.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
       Tasks: TOP => assets:precompile
       (See full trace by running task with --trace)
 !
 !     Precompiling assets failed.
 !
 !     Push rejected, failed to compile Ruby app.
 !     Push failed
```

**Comment by teerasej** [comment]
เกิดจากไฟล์ JS ใน `app/assets/javascripts/bootstrap` ที่ใส่เพิ่มเข้าไป แต่ยังไม่ได้ใช้
และ Uglify จะทำงานตอนจะเอาขึ้น Production (deploy ขึ้น heroku) เลยไม่พบ bug ตัวนี้ขณะทำการ dev ในเครื่อง

@rhearnorth ได้เอาออก และ deploy ขึ้นไปแล้ว ไม่มีปัญหา
